// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsBlockJumper
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSBlockJumper.Anthony Reddan.6d90d2bf-c317-4e02-97e2-ebdc4d657a76";
        public const string Name = "VSBlockJumper";
        public const string Description = @"Enables vertical navigation over blocks of code by allowing you to jump to the next blank line (above or below the cursor) adjacent to a block. This is similar to next/previous blank line in Vim.";
        public const string Language = "en-US";
        public const string Version = "1.1.3";
        public const string Author = "Anthony Reddan";
        public const string Tags = "code, navigation, jump, block, line, blank, down, up, previous, next, above, below, lines, move, caret, cursor, select, productivity, navigate, selection";
    }
}
